// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: contract/contract_reader.proto

package contract

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetListApprovalResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetListApprovalResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetListApprovalResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetListApprovalResponseMultiError, or nil if none found.
func (m *GetListApprovalResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetListApprovalResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetListApprovalResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetListApprovalResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetListApprovalResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetListApprovalResponseMultiError(errors)
	}

	return nil
}

// GetListApprovalResponseMultiError is an error wrapping multiple validation
// errors returned by GetListApprovalResponse.ValidateAll() if the designated
// constraints aren't met.
type GetListApprovalResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetListApprovalResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetListApprovalResponseMultiError) AllErrors() []error { return m }

// GetListApprovalResponseValidationError is the validation error returned by
// GetListApprovalResponse.Validate if the designated constraints aren't met.
type GetListApprovalResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetListApprovalResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetListApprovalResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetListApprovalResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetListApprovalResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetListApprovalResponseValidationError) ErrorName() string {
	return "GetListApprovalResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetListApprovalResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetListApprovalResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetListApprovalResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetListApprovalResponseValidationError{}

// Validate checks the field values on GetListTransferResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetListTransferResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetListTransferResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetListTransferResponseMultiError, or nil if none found.
func (m *GetListTransferResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetListTransferResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetListTransferResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetListTransferResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetListTransferResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetListTransferResponseMultiError(errors)
	}

	return nil
}

// GetListTransferResponseMultiError is an error wrapping multiple validation
// errors returned by GetListTransferResponse.ValidateAll() if the designated
// constraints aren't met.
type GetListTransferResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetListTransferResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetListTransferResponseMultiError) AllErrors() []error { return m }

// GetListTransferResponseValidationError is the validation error returned by
// GetListTransferResponse.Validate if the designated constraints aren't met.
type GetListTransferResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetListTransferResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetListTransferResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetListTransferResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetListTransferResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetListTransferResponseValidationError) ErrorName() string {
	return "GetListTransferResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetListTransferResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetListTransferResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetListTransferResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetListTransferResponseValidationError{}

// Validate checks the field values on RetrieveLatestBlockResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RetrieveLatestBlockResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RetrieveLatestBlockResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RetrieveLatestBlockResponseMultiError, or nil if none found.
func (m *RetrieveLatestBlockResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RetrieveLatestBlockResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Number

	// no validation rules for Nonce

	// no validation rules for Hash

	// no validation rules for GasLimit

	// no validation rules for GasUsed

	// no validation rules for Timestamp

	if len(errors) > 0 {
		return RetrieveLatestBlockResponseMultiError(errors)
	}

	return nil
}

// RetrieveLatestBlockResponseMultiError is an error wrapping multiple
// validation errors returned by RetrieveLatestBlockResponse.ValidateAll() if
// the designated constraints aren't met.
type RetrieveLatestBlockResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RetrieveLatestBlockResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RetrieveLatestBlockResponseMultiError) AllErrors() []error { return m }

// RetrieveLatestBlockResponseValidationError is the validation error returned
// by RetrieveLatestBlockResponse.Validate if the designated constraints
// aren't met.
type RetrieveLatestBlockResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetrieveLatestBlockResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetrieveLatestBlockResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetrieveLatestBlockResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetrieveLatestBlockResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetrieveLatestBlockResponseValidationError) ErrorName() string {
	return "RetrieveLatestBlockResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RetrieveLatestBlockResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetrieveLatestBlockResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetrieveLatestBlockResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetrieveLatestBlockResponseValidationError{}

// Validate checks the field values on RetrieveBalanceOfRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RetrieveBalanceOfRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RetrieveBalanceOfRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RetrieveBalanceOfRequestMultiError, or nil if none found.
func (m *RetrieveBalanceOfRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RetrieveBalanceOfRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RetrieveBalanceOfRequestMultiError(errors)
	}

	return nil
}

// RetrieveBalanceOfRequestMultiError is an error wrapping multiple validation
// errors returned by RetrieveBalanceOfRequest.ValidateAll() if the designated
// constraints aren't met.
type RetrieveBalanceOfRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RetrieveBalanceOfRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RetrieveBalanceOfRequestMultiError) AllErrors() []error { return m }

// RetrieveBalanceOfRequestValidationError is the validation error returned by
// RetrieveBalanceOfRequest.Validate if the designated constraints aren't met.
type RetrieveBalanceOfRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetrieveBalanceOfRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetrieveBalanceOfRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetrieveBalanceOfRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetrieveBalanceOfRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetrieveBalanceOfRequestValidationError) ErrorName() string {
	return "RetrieveBalanceOfRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RetrieveBalanceOfRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetrieveBalanceOfRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetrieveBalanceOfRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetrieveBalanceOfRequestValidationError{}

// Validate checks the field values on RetrieveBalanceOfResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RetrieveBalanceOfResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RetrieveBalanceOfResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RetrieveBalanceOfResponseMultiError, or nil if none found.
func (m *RetrieveBalanceOfResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RetrieveBalanceOfResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Balance

	// no validation rules for NativeBalance

	if len(errors) > 0 {
		return RetrieveBalanceOfResponseMultiError(errors)
	}

	return nil
}

// RetrieveBalanceOfResponseMultiError is an error wrapping multiple validation
// errors returned by RetrieveBalanceOfResponse.ValidateAll() if the
// designated constraints aren't met.
type RetrieveBalanceOfResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RetrieveBalanceOfResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RetrieveBalanceOfResponseMultiError) AllErrors() []error { return m }

// RetrieveBalanceOfResponseValidationError is the validation error returned by
// RetrieveBalanceOfResponse.Validate if the designated constraints aren't met.
type RetrieveBalanceOfResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetrieveBalanceOfResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetrieveBalanceOfResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetrieveBalanceOfResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetrieveBalanceOfResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetrieveBalanceOfResponseValidationError) ErrorName() string {
	return "RetrieveBalanceOfResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RetrieveBalanceOfResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetrieveBalanceOfResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetrieveBalanceOfResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetrieveBalanceOfResponseValidationError{}

// Validate checks the field values on SendTransactionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendTransactionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendTransactionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendTransactionRequestMultiError, or nil if none found.
func (m *SendTransactionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendTransactionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PrivKey

	// no validation rules for To

	// no validation rules for Amount

	if len(errors) > 0 {
		return SendTransactionRequestMultiError(errors)
	}

	return nil
}

// SendTransactionRequestMultiError is an error wrapping multiple validation
// errors returned by SendTransactionRequest.ValidateAll() if the designated
// constraints aren't met.
type SendTransactionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendTransactionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendTransactionRequestMultiError) AllErrors() []error { return m }

// SendTransactionRequestValidationError is the validation error returned by
// SendTransactionRequest.Validate if the designated constraints aren't met.
type SendTransactionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendTransactionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendTransactionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendTransactionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendTransactionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendTransactionRequestValidationError) ErrorName() string {
	return "SendTransactionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendTransactionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendTransactionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendTransactionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendTransactionRequestValidationError{}

// Validate checks the field values on SendTransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendTransactionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendTransactionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendTransactionResponseMultiError, or nil if none found.
func (m *SendTransactionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SendTransactionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SendTransactionResponseMultiError(errors)
	}

	return nil
}

// SendTransactionResponseMultiError is an error wrapping multiple validation
// errors returned by SendTransactionResponse.ValidateAll() if the designated
// constraints aren't met.
type SendTransactionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendTransactionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendTransactionResponseMultiError) AllErrors() []error { return m }

// SendTransactionResponseValidationError is the validation error returned by
// SendTransactionResponse.Validate if the designated constraints aren't met.
type SendTransactionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendTransactionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendTransactionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendTransactionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendTransactionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendTransactionResponseValidationError) ErrorName() string {
	return "SendTransactionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SendTransactionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendTransactionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendTransactionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendTransactionResponseValidationError{}

// Validate checks the field values on SendTransactionV2Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendTransactionV2Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendTransactionV2Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendTransactionV2RequestMultiError, or nil if none found.
func (m *SendTransactionV2Request) ValidateAll() error {
	return m.validate(true)
}

func (m *SendTransactionV2Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Signature

	// no validation rules for To

	// no validation rules for Amount

	if len(errors) > 0 {
		return SendTransactionV2RequestMultiError(errors)
	}

	return nil
}

// SendTransactionV2RequestMultiError is an error wrapping multiple validation
// errors returned by SendTransactionV2Request.ValidateAll() if the designated
// constraints aren't met.
type SendTransactionV2RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendTransactionV2RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendTransactionV2RequestMultiError) AllErrors() []error { return m }

// SendTransactionV2RequestValidationError is the validation error returned by
// SendTransactionV2Request.Validate if the designated constraints aren't met.
type SendTransactionV2RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendTransactionV2RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendTransactionV2RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendTransactionV2RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendTransactionV2RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendTransactionV2RequestValidationError) ErrorName() string {
	return "SendTransactionV2RequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendTransactionV2RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendTransactionV2Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendTransactionV2RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendTransactionV2RequestValidationError{}
