// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeContractReaderServiceServer is an autogenerated mock type for the UnsafeContractReaderServiceServer type
type UnsafeContractReaderServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedContractReaderServiceServer provides a mock function with given fields:
func (_m *UnsafeContractReaderServiceServer) mustEmbedUnimplementedContractReaderServiceServer() {
	_m.Called()
}

// NewUnsafeContractReaderServiceServer creates a new instance of UnsafeContractReaderServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeContractReaderServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeContractReaderServiceServer {
	mock := &UnsafeContractReaderServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
