version: "3.4"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-docker
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-docker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
      - "7545:7545"
    volumes:
      - ./ganache_data:/ganache_data

  mongodb:
    hostname: mongodb
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
    restart: always
