version: "3.4"

services:
  generate_contract:
    image: gen-contract
    build:
      context: ..
      target: gen-contract
      dockerfile: ./developments/sol.Dockerfile
    volumes:
      - "../contracts:/app/contracts"
      - "./gen-sol.sh:/app/gen-sol.sh"
      - "../idl:/app/idl"
    entrypoint: sh /app/gen-sol.sh
