eth_client: 
  host: "http://ganache"
  port: "8545"
ws_eth_client: 
  host: "ws://ganache"
  port: "8545"
contract_reader_service:
  host: ""
  port: "5002"
user_service:
  host: "user"
  port: "5001"
mongo_db:
  schema: mongodb
  host: mongodb
  port: "27017"
  database: blockchain
kafka:
  host: kafka
  port: "9092"